{% set name = "napari-plot" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari_plot-{{ version }}.tar.gz
  sha256: 41f935fb5cc4ff9e7ab3c9b5d207cba37b5384eaff0b7c6f4d6388795949f88b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - napari ==0.4.12
    - napari-plugin-engine >=0.1.4
    - numpy
    - python >=3.7
    - qtawesome
    - qtpy

test:
  imports:
    - napari_plot
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lukasz-migas/napari-1d
  summary: Plugin providing support for 1d plotting in napari.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/napari
    - lukasz-migas
